import 'package:kreyno/services/api/dio_service.dart';
import 'package:kreyno/services/auth_service.dart';
import 'package:kreyno/services/cars_service.dart';
import 'package:kreyno/services/device_service.dart';
import 'package:kreyno/services/media_service.dart';
import 'package:kreyno/services/onboarding_service.dart';
import 'package:kreyno/services/permissions_service.dart';
import 'package:kreyno/services/picked_language_service.dart';
import 'package:kreyno/services/shared_prefs_service.dart';
import 'package:kreyno/services/stripe_service.dart';
import 'package:kreyno/services/toast_service.dart';
import 'package:kreyno/services/user_service.dart';
import 'package:kreyno/ui/bottom_sheets/notice/notice_sheet.dart';
import 'package:kreyno/ui/views/home/home_view.dart';
import 'package:kreyno/ui/views/startup/startup_view.dart';
import 'package:stacked/stacked_annotations.dart';
import 'package:stacked_services/stacked_services.dart';
import 'package:kreyno/ui/views/onboarding/onboarding_view.dart';
import 'package:kreyno/ui/views/signin/signin_view.dart';
import 'package:kreyno/ui/views/signup/signup_view.dart';
import 'package:kreyno/ui/views/set_up_vehicule/set_up_vehicule_view.dart';
import 'package:kreyno/ui/views/set_up_payment_methods/set_up_payment_methods_view.dart';
import 'package:kreyno/ui/views/set_up_permissions/set_up_permissions_view.dart';
import 'package:kreyno/ui/views/seller_spot_details/seller_spot_details_view.dart';
import 'package:kreyno/ui/views/buyer_spot_details/buyer_spot_details_view.dart';
import 'package:kreyno/ui/views/spot_sold_success/spot_sold_success_view.dart';
import 'package:kreyno/ui/views/spot_bought_success/spot_bought_success_view.dart';
import 'package:kreyno/ui/views/edit_profile/edit_profile_view.dart';
import 'package:kreyno/ui/views/my_vehicules/my_vehicules_view.dart';
import 'package:kreyno/ui/views/my_payment_methodes/my_payment_methodes_view.dart';
import 'package:kreyno/ui/views/spots_history/spots_history_view.dart';
import 'package:kreyno/ui/views/kreyno_wallet/kreyno_wallet_view.dart';
import 'package:kreyno/ui/views/cashout/cashout_view.dart';
import 'package:kreyno/ui/views/edit_vehicule/edit_vehicule_view.dart';
import 'package:kreyno/ui/bottom_sheets/otp/otp_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/upload_vehicule_image/upload_vehicule_image_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/buy_spot/buy_spot_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/pay_for_spot/pay_for_spot_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/add_payment_method/add_payment_method_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/cancelation_reasons/cancelation_reasons_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/home_filter/home_filter_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/create_spot/create_spot_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/rejection_reasons/rejection_reasons_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/profile/profile_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/danger/danger_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/date_picker_filter/date_picker_filter_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/completed_action/completed_action_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/add_payment_cart/add_payment_cart_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/logout_confirmation/logout_confirmation_sheet.dart';
import 'package:kreyno/ui/bottom_sheets/delete_account_confirmation/delete_account_confirmation_sheet.dart';
import 'package:kreyno/ui/views/my_stationements/my_stationements_view.dart';
import 'package:kreyno/ui/views/kreyono_portfolio/kreyono_portfolio_view.dart';
import 'package:kreyno/ui/views/checkout_money/checkout_money_view.dart';
import 'package:kreyno/ui/bottom_sheets/checkout_money_feedback/checkout_money_feedback_sheet.dart';
import 'package:kreyno/ui/views/add_vehicule/add_vehicule_view.dart';
import 'package:kreyno/ui/views/set_up_language/set_up_language_view.dart';
import 'package:kreyno/ui/bottom_sheets/country_code_picker/country_code_picker_sheet.dart';
import 'package:kreyno/ui/dialogs/destructive/destructive_dialog.dart';
import 'package:kreyno/ui/views/account_settings/account_settings_view.dart';
import 'package:kreyno/ui/views/change_language/change_language_view.dart';
import 'package:kreyno/ui/views/change_phone_number/change_phone_number_view.dart';
import 'package:kreyno/ui/bottom_sheets/upload_profile_image/upload_profile_image_sheet.dart';
// @stacked-import

@StackedApp(
  logger: StackedLogger(),
  routes: [
    MaterialRoute(page: HomeView),
    MaterialRoute(page: StartupView),
    MaterialRoute(page: OnboardingView),
    MaterialRoute(page: SigninView),
    MaterialRoute(page: SignupView),
    MaterialRoute(page: SetUpVehiculeView),
    MaterialRoute(page: SetUpPaymentMethodsView),
    MaterialRoute(page: SetUpPermissionsView),
    MaterialRoute(page: SellerSpotDetailsView),
    MaterialRoute(page: BuyerSpotDetailsView),
    MaterialRoute(page: SpotSoldSuccessView),
    MaterialRoute(page: SpotBoughtSuccessView),
    MaterialRoute(page: EditProfileView),
    MaterialRoute(page: MyVehiculesView),
    MaterialRoute(page: MyPaymentMethodesView),
    MaterialRoute(page: SpotsHistoryView),
    MaterialRoute(page: KreynoWalletView),
    MaterialRoute(page: CashoutView),
    MaterialRoute(page: EditVehiculeView),
    MaterialRoute(page: SetUpLanguageView),
    MaterialRoute(page: MyStationementsView),
    MaterialRoute(page: KreyonoPortfolioView),
    MaterialRoute(page: CheckoutMoneyView),
    MaterialRoute(page: AddVehiculeView),
    MaterialRoute(page: AccountSettingsView),
    MaterialRoute(page: ChangeLanguageView),
    MaterialRoute(page: ChangePhoneNumberView),
    // @stacked-route
  ],
  dependencies: [
    LazySingleton(classType: BottomSheetService),
    LazySingleton(classType: DialogService),
    LazySingleton(classType: NavigationService),
    LazySingleton(classType: SharedPrefsService),
    Singleton(classType: DioService),
    LazySingleton(classType: AuthService),
    LazySingleton(classType: ToastService),
    LazySingleton(classType: DeviceService),
    LazySingleton(classType: OnboardingService),
    LazySingleton(classType: PickedLanguageService),
    LazySingleton(classType: UserService),
    LazySingleton(classType: CarsService),
    LazySingleton(classType: MediaService),
    LazySingleton(classType: StripeService),
    LazySingleton(classType: PermissionsService),
    // @stacked-service
  ],
  bottomsheets: [
    StackedBottomsheet(classType: NoticeSheet),
    StackedBottomsheet(classType: OtpSheet),
    StackedBottomsheet(classType: UploadVehiculeImageSheet),
    StackedBottomsheet(classType: BuySpotSheet),
    StackedBottomsheet(classType: PayForSpotSheet),
    StackedBottomsheet(classType: AddPaymentMethodSheet),
    StackedBottomsheet(classType: CancelationReasonsSheet),
    StackedBottomsheet(classType: HomeFilterSheet),
    StackedBottomsheet(classType: CreateSpotSheet),
    StackedBottomsheet(classType: RejectionReasonsSheet),
    StackedBottomsheet(classType: ProfileSheet),
    StackedBottomsheet(classType: DangerSheet),
    StackedBottomsheet(classType: DatePickerFilterSheet),
    StackedBottomsheet(classType: CompletedActionSheet),
    StackedBottomsheet(classType: AddPaymentCartSheet),
    StackedBottomsheet(classType: LogoutConfirmationSheet),
    StackedBottomsheet(classType: DeleteAccountConfirmationSheet),
    StackedBottomsheet(classType: CheckoutMoneyFeedbackSheet),
    StackedBottomsheet(classType: CountryCodePickerSheet),
    StackedBottomsheet(classType: UploadProfileImageSheet),
    // @stacked-bottom-sheet
  ],
  dialogs: [
    StackedDialog(classType: DestructiveDialog),
    // @stacked-dialog
  ],
)
class App {}
